name: Lint and Format Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=0

  format:
    name: Run Prettier
    runs-on: ubuntu-latest
    needs: lint  # This ensures Prettier runs only if the lint job completes successfully.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Prettier
        run: |
          npx prettier --check "**/*.{js,jsx,ts,tsx,css,scss,html,json,md}"
